CREATE TABLE IF NOT EXISTS `todolist` (
	`id` int PRIMARY KEY AUTO_INCREMENT,
	`title` varchar(255) NOT NULL,
	`author` int NOT NULL,
	`state` int(1) NOT NULL,
	`created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);